hydra:
  run:
    dir: logs  # ログ保存ディレクトリ

random_seed: 42
source_speaker: "jvs001"
target_speaker: "jvs010"

path:
  corpus_dir: "../corpus/jvs_ver1"
  output_base_dir: "./output"
  output_tag:
    split_info: "split_info.json"
    feature: "feature"
    checkpoint: "checkpoint"
    train_log: "train_log"
    eval: "eval"

data:
  validation_size: 2
  test_size: 2
  split_mode: "fixed" # "random"
  sample_rate: 24000
  frame_period: 5.0
  audio_max_value: 0.95
  top_db: 60
  f0_floor: 60
  f0_ceil: 550
  mcep_order: 25  # 24000Hzの場合は40が一般的
  mcep_0dim_threshold: -10

train:
  model:
    hidden_dim: 512    # 隠れ層次元数
    dropout_rate: 0.2  # ドロップアウト率
  optimizer:  # Adamを使用します
    learning_rate: 1e-4
    weight_decay: 1e-5
    betas: [0.9, 0.999]
  epoch: 20
  batch_size: 128
  num_workers: 0
  pin_memory: true
  shuffle: true
  device: "cpu"  # "cpu", "mps", "cuda", "cuda:0", "cuda:1", ...
  logging:
    interval: 10
    keep_latest: true
  eval:
    interval: 1

eval:
  checkpoint_name: "latest.pth"